import { Dish, Table, Order } from "@/types/restaurant";

export const mockDishes: Dish[] = [
  {
    id: "1",
    name: "Burger Clásico",
    description: "Jugosa hamburguesa con queso, lechuga y tomate",
    price: 8.99,
    category: "principal",
    prepTime: 12,
    image: "🍔",
  },
  {
    id: "2",
    name: "Pollo Frito Crujiente",
    description: "Pechuga de pollo crujiente servida con papas",
    price: 9.99,
    category: "principal",
    prepTime: 15,
    image: "🍗",
  },
  {
    id: "3",
    name: "Sándwich de Pollo",
    description: "Pan tostado con pollo a la parrilla, aguacate y mayonesa",
    price: 7.99,
    category: "principal",
    prepTime: 10,
    image: "🥪",
  },
  {
    id: "4",
    name: "Papas Fritas",
    description: "Papas fritas crujientes con sal",
    price: 3.49,
    category: "lado",
    prepTime: 8,
    image: "🍟",
  },
  {
    id: "5",
    name: "Aros de Cebolla",
    description: "Aros de cebolla rebozados y fritos",
    price: 4.49,
    category: "lado",
    prepTime: 10,
    image: "🧅",
  },
  {
    id: "6",
    name: "Ensalada Fresca",
    description: "Ensalada con lechuga, tomate, pepino y aderezo de la casa",
    price: 6.99,
    category: "lado",
    prepTime: 5,
    image: "🥗",
  },
  {
    id: "7",
    name: "Refresco",
    description: "Refresco frío (Cola, Limón, Naranja)",
    price: 2.49,
    category: "bebida",
    prepTime: 2,
    image: "🥤",
  },
  {
    id: "8",
    name: "Jugo Natural",
    description: "Jugo recién exprimido (Naranja, Piña, Sandía)",
    price: 3.99,
    category: "bebida",
    prepTime: 3,
    image: "🧃",
  },
  {
    id: "9",
    name: "Helado",
    description: "Helado cremoso (Vainilla, Chocolate, Fresa)",
    price: 3.99,
    category: "postre",
    prepTime: 2,
    image: "🍦",
  },
  {
    id: "10",
    name: "Tiramisú",
    description: "Tiramisú tradicional italiano",
    price: 5.99,
    category: "postre",
    prepTime: 1,
    image: "🍰",
  },
];

export const mockTables: Table[] = [
  {
    id: "t1",
    number: 1,
    capacity: 2,
    status: "occupied",
    partySize: 2,
    currentOrder: {
      id: "o1",
      tableId: "t1",
      items: [
        {
          id: "oi1",
          dishId: "1",
          quantity: 2,
          status: "preparing",
          startedAt: new Date(Date.now() - 5 * 60000),
        },
        {
          id: "oi2",
          dishId: "4",
          quantity: 2,
          status: "ready",
          completedAt: new Date(Date.now() - 2 * 60000),
        },
      ],
      status: "active",
      createdAt: new Date(Date.now() - 10 * 60000),
      total: 25.96,
    },
  },
  {
    id: "t2",
    number: 2,
    capacity: 4,
    status: "available",
  },
  {
    id: "t3",
    number: 3,
    capacity: 4,
    status: "occupied",
    partySize: 3,
    currentOrder: {
      id: "o2",
      tableId: "t3",
      items: [
        {
          id: "oi3",
          dishId: "2",
          quantity: 1,
          status: "pending",
        },
        {
          id: "oi4",
          dishId: "3",
          quantity: 2,
          status: "pending",
        },
        {
          id: "oi5",
          dishId: "7",
          quantity: 3,
          status: "pending",
        },
      ],
      status: "active",
      createdAt: new Date(Date.now() - 2 * 60000),
      total: 35.94,
    },
  },
  {
    id: "t4",
    number: 4,
    capacity: 2,
    status: "reserved",
  },
  {
    id: "t5",
    number: 5,
    capacity: 6,
    status: "available",
  },
  {
    id: "t6",
    number: 6,
    capacity: 4,
    status: "occupied",
    partySize: 4,
    currentOrder: {
      id: "o3",
      tableId: "t6",
      items: [
        {
          id: "oi6",
          dishId: "1",
          quantity: 1,
          status: "ready",
          completedAt: new Date(Date.now() - 8 * 60000),
        },
      ],
      status: "active",
      createdAt: new Date(Date.now() - 15 * 60000),
      total: 8.99,
    },
  },
];

export const mockOrders: Order[] = mockTables
  .filter((t) => t.currentOrder)
  .map((t) => t.currentOrder!);
